services:
  neo4j:
    # Best practice is to pin to a specific major version for stability.
    image: neo4j:5.26.8
    ports:
      - "7474:7474"  # HTTP Browser interface
      - "7687:7687"  # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/saga_password
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/conf:/conf
      - ./neo4j/plugins:/plugins
    restart: unless-stopped
