services:
  neo4j:
    # Best practice is to pin to a specific major version for stability.
    image: neo4j:5
    ports:
      - "7474:7474"  # HTTP Browser interface
      - "7687:7687"  # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/saga_password
      # --- START: Corrected APOC Plugin Config ---
      # Tells Neo4j to download and install the APOC plugin.
      - NEO4J_PLUGINS=["apoc"]
      # For Neo4j 5.x, 'allowlist' must be used instead of 'unrestricted'.
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      # You must accept the license agreement to use APOC core procedures in Neo4j 5+.
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      # --- END: Corrected APOC Plugin Config ---
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/conf:/conf
      # Mount the plugins directory to persist plugins across container restarts.
      - ./neo4j/plugins:/plugins
    restart: unless-stopped
