# core/langgraph/export.py
"""Export project chapter files into consolidated artifacts."""

from __future__ import annotations

import hashlib
import re
from collections.abc import Iterable
from pathlib import Path

from core.langgraph.manuscript import ManuscriptStore
from utils.file_io import ContainedFiles


def _publish_export(files: ContainedFiles, path: str, content: bytes) -> None:
    """Retain generated bytes before replacement; never overwrite unowned edits."""
    retained_directory = f"exports/.generated/{Path(path).name}"
    previous = files.read_bytes(path) if files.exists(path) else None
    if previous is not None and previous != content:
        previous_path = f"{retained_directory}/{hashlib.sha256(previous).hexdigest()}.md"
        if not files.exists(previous_path) or files.read_bytes(previous_path) != previous:
            raise ValueError(f"Unowned export requires explicit reconciliation: {path}")
    retained_path = f"{retained_directory}/{hashlib.sha256(content).hexdigest()}.md"
    files.write_bytes(retained_path, content, create_only=True)
    if previous != content:
        files.write_bytes(path, content)
    if files.read_bytes(path) != content:
        raise ValueError("Export publication readback mismatch")


def _iter_chapter_files(chapters_dir: Path) -> Iterable[Path]:
    """Discover historical Markdown for the explicitly unverified export only."""
    files = ContainedFiles(chapters_dir.parent)
    chapter_files: list[tuple[int, Path]] = []
    for name in files.list_names(chapters_dir.name):
        match = re.fullmatch(r"chapter_([0-9]+)\.md", name)
        if match is not None:
            chapter_files.append((int(match[1]), chapters_dir / name))
    chapter_files.sort(key=lambda item: item[0])
    numbers = [number for number, _ in chapter_files]
    if not numbers or numbers != list(range(1, len(numbers) + 1)):
        raise ValueError("Legacy export requires a nonempty contiguous chapter sequence without duplicate identities")
    return [path for _, path in chapter_files]


def _extract_body(content: str) -> str:
    """Remove only exact opening/closing delimiter lines; preserve all body text.

    Unterminated front matter is prose. LF, CRLF and CR delimiters are recognized
    without normalizing line endings, whitespace, BOMs or literal escapes.
    """
    opening = re.match(r"---(\r\n|\n|\r)", content)
    if opening is not None:
        closing = re.search(r"(?:\A|(?<=[\r\n]))---(?:" + re.escape(opening[1]) + r"|\Z)", content[opening.end():])
        if closing is not None:
            return content[opening.end() + closing.end():]
    return content


def generate_legacy_export(project_dir: str | Path) -> Path:
    """Explicitly export unverified historical Markdown without accepting it.

    Args:
        project_dir: Project root directory containing `chapters/` and `exports/`.

    Returns:
        Path to the unverified export (`exports/novel_legacy_unverified.md`).
        Empty, gapped or duplicate chapter sequences raise before publication.

    Notes:
        - Chapters are discovered from `chapters/chapter_<NNN>.md` files and sorted by
          the numeric component.
        - YAML front matter is removed when present and well-formed.
        - Exact bodies are joined with two separator newlines and a terminal
          newline if needed, matching the accepted-manuscript export policy.
    """
    project_path = Path(project_dir)
    chapters_dir = project_path / "chapters"
    exports_dir = project_path / "exports"
    output_path = exports_dir / "novel_legacy_unverified.md"
    files = ContainedFiles(project_path, durable=True)

    chapter_files = list(_iter_chapter_files(chapters_dir))

    bodies: list[str] = []
    for chapter_path in chapter_files:
        raw = files.read_bytes(chapter_path.relative_to(project_path).as_posix()).decode("utf-8")
        body = _extract_body(raw)
        if not body:
            raise ValueError(f"Empty legacy chapter body: {chapter_path.name}")
        bodies.append(body)

    final_text = "\n\n".join(bodies)
    if not final_text.endswith("\n"):
        final_text += "\n"

    _publish_export(files, output_path.relative_to(project_path).as_posix(), final_text.encode("utf-8"))

    return output_path


def accepted_chapter_numbers(project_dir: Path) -> list[int]:
    """Read checksum-verified accepted identities, without consulting draft mirrors."""
    store = ManuscriptStore(project_dir)
    chapter_numbers = []
    for name in store.files.list_names("chapters"):
        if name.endswith(".accepted.json"):
            match = re.fullmatch(r"chapter_([0-9]+)\.accepted\.json", name)
            if match is None or name != f"chapter_{int(match[1]):03d}.accepted.json":
                raise ValueError("Invalid accepted manuscript filename")
            number = int(match[1])
            store.accepted(number)
            chapter_numbers.append(number)
    return sorted(chapter_numbers)


def generate_full_export(project_dir: str | Path, *, expected_chapters: int | None = None) -> Path:
    """Export only checksum-verified accepted manuscripts, in chapter order.

    Bodies are consumed byte-for-byte, with two separator newlines between them
    and a terminal newline if needed. Compatibility mirrors never supply prose.
    Historical unreceipted Markdown requires generate_legacy_export explicitly.
    Without expected_chapters this is an accepted-only preview and retains the
    existing empty no-op API. Complete writer exports must supply the configured
    positive chapter count; missing, extra and gapped chapters reject the write.
    """
    project_path = Path(project_dir)
    store = ManuscriptStore(project_path)
    chapter_numbers = accepted_chapter_numbers(project_path)
    if expected_chapters is not None:
        if type(expected_chapters) is not int or expected_chapters <= 0:
            raise ValueError("Expected chapter count must be a positive integer")
        if chapter_numbers != list(range(1, expected_chapters + 1)):
            raise ValueError(f"Expected accepted chapters 1 through {expected_chapters}; found {chapter_numbers}")
    output_path = project_path / "exports/novel_full.md"
    if not chapter_numbers:
        return output_path
    bodies = [store.read(store.accepted(number))[1] for number in sorted(chapter_numbers)]
    content = b"\n\n".join(bodies)
    if not content.endswith(b"\n"):
        content += b"\n"
    _publish_export(store.files, "exports/novel_full.md", content)
    return output_path
