# config/docs_generator.py
"""Generate configuration reference documentation from the settings model.

This module renders declared field types, defaults and descriptions from SagaSettings.
It never publishes active settings values. Factory-backed groups are labeled rather
than instantiated, because BaseSettings factories can consume private environment values.

Side effects:
- Writing the generated Markdown file to disk.

Notes:
    Importing this module imports [`config.settings`](config/settings.py:1), which has
    import-time side effects (directory creation and logging configuration). Use this
    generator in environments where those side effects are acceptable.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from .settings import SagaSettings


def _format_default(value: Any) -> str:
    """Format a settings value for display in Markdown.

    Args:
        value: Declared field default, not a value from the active settings instance.

    Returns:
        A compact string representation suitable for a Markdown table cell.
    """
    if isinstance(value, str):
        return f'"{value}"'
    if isinstance(value, int | float | bool):
        return str(value)
    if isinstance(value, list | tuple | set):
        return f"{list(value)}"
    # Fallback for other types
    return repr(value)


def generate_docs(
    output_path: str | os.PathLike = "docs/generated_configuration_schema.md",
) -> None:
    """Generate a Markdown file documenting all configuration fields.

    Args:
        output_path: Destination path for the generated documentation. Parent
            directories are created automatically.

    Raises:
        OSError: If the destination cannot be created or written.
    """
    # Ensure the output directory exists
    out_file = Path(output_path)
    out_file.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Generated Configuration Schema",
        "",
        "This file is automatically generated from the ``SagaSettings`` model "
        "and should be kept in sync with the source code.  It is intended for "
        "human readers and can be referenced by the project documentation.",
        "",
        "| Setting | Type | Default | Description |",
        "|---------|------|---------|-------------|",
    ]

    # Iterate over the model fields in definition order
    for field_name, field_info in SagaSettings.model_fields.items():
        field_type = field_info.annotation
        type_str = getattr(field_type, "__name__", str(field_type))
        type_str = type_str.replace("|", "\\|")

        if field_info.exclude or not field_info.repr:
            default_str = "(redacted)"
        elif field_info.default_factory is not None:
            default_str = "(settings group; see declared model defaults)"
        else:
            default_str = _format_default(field_info.default)
        default_str = default_str.replace("|", "\\|").replace("\n", "<br>")

        description = field_info.description.replace("\n", " ").strip() if field_info.description else ""

        description = description.replace("|", "\\|")

        lines.append(f"| {field_name} | {type_str} | {default_str} | {description} |")

    # Write the file
    out_file.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    generate_docs()
